- assert:
    that:
      - json_policy is defined
      - deny_groups is iterable or deny_groups is not defined

- name: Load JSON file
  set_fact:
    policy: "{{ lookup('file', '{{json_policy}}') | from_json }}"

- name: Set Variables
  set_fact:
    domain: "{{ policy.domain_info.domain }}"
    crt: "{{ policy.domain_info.crt }}"
    key: "{{ policy.domain_info.key }}"
    uri: "{{ policy.domain_info.uri }}"
    dn: "{{ ['dc='] | product( policy.domain_info.domain.split('.') ) | map('join') | join(',')}}"
    allowed_groups: "{{ policy.groups | map(attribute='name') | difference ( deny_groups | default(policy.exclude) ) | join(',') }}"

- name: Install Package Dependencies
  apt:
    pkg:
     - sssd-ldap
     - ldap-utils
    state: latest
    update_cache: yes
  tags:
    - install

- name: Copy file Dependencies to host
  copy: 
    src: "{{ item }}"
    dest:  /etc/sssd/
    mode: 0400
  loop:
    - "{{ crt }}" 
    - "{{ key }}" 
  register: files
  tags:
    - install

- name: Enable Pam User Directory Creation
  command: pam-auth-update --force --enable mkhomedir
  tags:
    - install

- name: Write Configurations from templates
  template:
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}" 
    mode: "{{ item.mode | default(400)}}" 
    backup: yes
  loop:
    - src: sssd.conf.j2
      dest: /etc/sssd/sssd.conf
    - src: 00-ldap-operator-roles.j2
      dest: /etc/sudoers.d/00-ldap-operator-roles
    - src: 01-ldap-operator-policies.j2
      dest: /etc/sudoers.d/01-ldap-operator-policies
    - src: get-ldaps-pubkey.sh.j2
      dest: /etc/sssd/get-ldaps-pubkey.sh
      mode: 500
    - src: 02-sshd-enable-ldap-pki.conf.j2
      dest: /etc/ssh/sshd_config.d/02-sshd-enable-ldap-pki.conf

- name: Start & Enable Services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - sssd
    - sshd

